version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    reviewers:
      - "KevinTCoughlin"
    assignees:
      - "KevinTCoughlin"

  # Swift Package Manager dependencies (when external deps are added)
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "swift"
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    reviewers:
      - "KevinTCoughlin"
    assignees:
      - "KevinTCoughlin"
    
  # Docker dependencies (for DevContainer)
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
      - "devcontainer"
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    reviewers:
      - "KevinTCoughlin"
    assignees:
      - "KevinTCoughlin"